! ============================================================================
! Name        : readT3.f90
! Author      : Biaobin Li
! Version     : V-1.0
! Copyright   : Your copyright notice
! Description : get the phase spaces out of TAPE3.T3, which is generated by
!               Parmela, for benchmark with IMPACT-T
!               sister program: readT3.f90 & readfort10ij.f90
! ============================================================================

program readT3
    implicit none
    real*8 :: x,bgx,y,bgy,z,bgz,species,charge
    character(len=100) :: line,filename
    integer :: i,j,pos
    integer :: np,cnt,phanum

    open(10,file='TAPE3.T3',status='old')

    open(2,file='parm_phase.txt')
    open(3,file='parm_id.txt')

    read(10,'(A)')line

    cnt=1
    phanum=0
    write(3,*) cnt
    do while (.true.)

      if (index(line,"Number of particles:")==1) then
         !get the particles number
         pos = index(line,"Number of particles:")+len_trim("Number of particles:")+1
         read(line(pos:),*) np

         ! skip the headline
         read(10,'(A)') line

         !write the following lines into file phase.txt
         do j=1,np
           read(10,*)x,bgx,y,bgy,z,bgz,species,charge
           write(2,101)x,bgx,y,bgy,z,bgz
         enddo

         !get the start line number in phase.txt
         cnt = cnt+np
         write(3,*) cnt
         
         !phase space number
         phanum = phanum+1
         print*,"phase # read:",phanum

      endif

      ! read the next line
      read(10,'(A)',iostat=i) line
      if(i /= 0) exit

    enddo

close(10)
close(2)
close(3)

print*,"Data extracted from TAPE3.T3 finished."

101 format(6(1x,e20.12))

end program
