#!/usr/bin/env python3

import sys
import impactt_parser as impt

if len(sys.argv) != 3:
   print("\n Please give *.impz file and LineName, usage: genimpactzin tmp.impz LineName \n")
   exit()

file = sys.argv[1] 
line= sys.argv[2]

tmp = impt.impactt_parser(file, line)
tmp.write_impacttin()    


